import "./globals.css";
import { themeClass } from "./components/theme.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={themeClass}>
        {children}
      </body>
    </html>
  );
}
